/**
 * Cloudflare Sync API Worker — D1 REST Proxy
 *
 * Provides an authenticated REST API that desktop clients call to:
 * - Sync thread metadata (read/unread, archive, star)
 * - Manage drafts (stored in D1 for cross-client sync)
 * - List identities
 * - Record sent messages
 * - Pull/push sync state (cursor-based)
 *
 * Authentication: Bearer token stored as a Cloudflare secret (MAIL_SYNC_TOKEN).
 * Set via: wrangler secret put MAIL_SYNC_TOKEN
 */

// ── Environment ───────────────────────────────────────────────────────────────
// DB is generated by `wrangler types` from wrangler.toml [[d1_databases]].
// MAIL_SYNC_TOKEN is a secret — not in wrangler.toml, so we declare it here.
export interface Env {
  DB: D1Database;
  MAIL_SYNC_TOKEN: string;
}

// ── Domain shapes (request/response bodies) ───────────────────────────────────

interface IdentityBody {
  id: string;
  address: string;
  display_name?: string;
  identity_type?: "mailbox" | "send_only";
}

interface ThreadBody {
  id: string;
  subject: string;
  identity_id: string;
  last_message_at: string;
  message_count?: number;
  is_read?: boolean;
  is_starred?: boolean;
  is_archived?: boolean;
  is_trashed?: boolean;
  snippet?: string;
  participant_names?: string;
  created_at?: string;
}

interface MessageBody {
  id: string;
  thread_id: string;
  message_id: string;
  in_reply_to?: string;
  references?: string[];
  from_address: string;
  from_name?: string;
  to_addresses?: string[];
  cc_addresses?: string[];
  bcc_addresses?: string[];
  reply_to?: string;
  subject: string;
  body_text?: string;
  body_html?: string;
  snippet?: string;
  original_to?: string;
  direction?: "inbound" | "outbound";
  imap_uid?: number | null;
  resend_id?: string | null;
  is_read?: boolean;
  is_draft?: boolean;
  has_attachments?: boolean;
  received_at?: string;
}

interface DraftBody {
  id?: string;
  thread_id?: string | null;
  identity_id: string;
  to_addresses?: string[];
  cc_addresses?: string[];
  bcc_addresses?: string[];
  subject?: string;
  body_text?: string;
  body_html?: string;
  in_reply_to?: string;
  references?: string[];
  is_reply?: boolean;
  created_at?: string;
}

interface SyncPullBody {
  client_id: string;
  d1_cursor?: string;
}

interface SyncPushBody {
  client_id: string;
  messages?: MessageBody[];
  threads?: ThreadBody[];
  drafts?: DraftBody[];
  last_imap_uid?: number;
}

// ── Worker entry point ────────────────────────────────────────────────────────

export default {
  async fetch(
    request: Request,
    env: Env,
    _ctx: ExecutionContext
  ): Promise<Response> {
    // ── Auth ───────────────────────────────────────────────────────────────────
    const authHeader = request.headers.get("Authorization") ?? "";
    if (!authHeader.startsWith("Bearer ") || authHeader.slice(7) !== env.MAIL_SYNC_TOKEN) {
      return json({ error: "Unauthorized" }, 401);
    }

    const url = new URL(request.url);
    const path = url.pathname;
    const method = request.method;

    // ── Router ─────────────────────────────────────────────────────────────────
    try {
      // Identities
      if (path === "/api/v1/identities" && method === "GET") {
        return await listIdentities(env);
      }
      if (path === "/api/v1/identities" && method === "POST") {
        return await upsertIdentity(env, await request.json<IdentityBody>());
      }

      // Threads (paginated)
      if (path.startsWith("/api/v1/threads") && !path.includes("/api/v1/threads/") && method === "GET") {
        return await listThreads(env, url.searchParams);
      }
      if (path.match(/^\/api\/v1\/threads\/[^/]+$/) && method === "GET") {
        const id = path.split("/").pop()!;
        return await getThread(env, id);
      }
      if (path === "/api/v1/threads" && method === "POST") {
        return await upsertThread(env, await request.json<ThreadBody>());
      }

      // Messages
      if (path === "/api/v1/messages" && method === "POST") {
        return await saveMessage(env, await request.json<MessageBody>());
      }
      if (path === "/api/v1/sent" && method === "POST") {
        return await saveMessage(env, await request.json<MessageBody>());
      }

      // Drafts
      if (path === "/api/v1/drafts" && method === "GET") {
        return await listDrafts(env);
      }
      if (path === "/api/v1/drafts" && method === "POST") {
        return await saveDraft(env, await request.json<DraftBody>());
      }
      if (path.match(/^\/api\/v1\/drafts\/[^/]+$/) && method === "DELETE") {
        const id = path.split("/").pop()!;
        return await deleteDraft(env, id);
      }

      // Sync
      if (path === "/api/v1/sync/pull" && method === "POST") {
        return await syncPull(env, await request.json<SyncPullBody>());
      }
      if (path === "/api/v1/sync/push" && method === "POST") {
        return await syncPush(env, await request.json<SyncPushBody>());
      }

      return json({ error: "Not found" }, 404);
    } catch (err) {
      console.error("API error:", err);
      return json({ error: "Internal server error", detail: String(err) }, 500);
    }
  },
} satisfies ExportedHandler<Env>;

// ── Identities ────────────────────────────────────────────────────────────────

async function listIdentities(env: Env): Promise<Response> {
  const { results } = await env.DB.prepare(
    "SELECT * FROM identities WHERE is_active = 1 ORDER BY created_at ASC"
  ).all();
  return json({ identities: results });
}

async function upsertIdentity(env: Env, body: IdentityBody): Promise<Response> {
  const now = new Date().toISOString();
  await env.DB.prepare(`
    INSERT INTO identities (id, address, display_name, identity_type, is_active, created_at, updated_at)
    VALUES (?, ?, ?, ?, 1, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      display_name = excluded.display_name,
      identity_type = excluded.identity_type,
      is_active = excluded.is_active,
      updated_at = excluded.updated_at
  `).bind(body.id, body.address, body.display_name, body.identity_type ?? "mailbox", now, now).run();
  return json({ ok: true });
}

// ── Threads ───────────────────────────────────────────────────────────────────

async function listThreads(env: Env, params: URLSearchParams): Promise<Response> {
  const identityID = params.get("identity") ?? "";
  const limit = Math.min(parseInt(params.get("limit") ?? "30"), 100);
  const cursor = params.get("cursor") ?? "";

  let query = "SELECT * FROM threads WHERE is_archived = 0 AND is_trashed = 0";
  const binds: (string | number)[] = [];

  if (identityID) {
    query += " AND identity_id = ?";
    binds.push(identityID);
  }
  if (cursor) {
    query += " AND last_message_at < ?";
    binds.push(cursor);
  }
  query += " ORDER BY last_message_at DESC LIMIT ?";
  binds.push(limit + 1); // fetch one extra to determine if there's a next page

  const { results } = await env.DB.prepare(query).bind(...binds).all();

  const hasMore = results.length > limit;
  const threads = hasMore ? results.slice(0, limit) : results;
  const nextCursor = hasMore ? (threads[threads.length - 1].last_message_at as string) : "";

  // Count total.
  let countQuery = "SELECT COUNT(*) as total FROM threads WHERE is_archived = 0 AND is_trashed = 0";
  const countBinds: string[] = [];
  if (identityID) {
    countQuery += " AND identity_id = ?";
    countBinds.push(identityID);
  }
  const { results: countRes } = await env.DB.prepare(countQuery).bind(...countBinds).all();
  const total = (countRes[0] as { total: number } | undefined)?.total ?? 0;

  return json({ threads, next_cursor: nextCursor, total });
}

async function getThread(env: Env, id: string): Promise<Response> {
  const thread = await env.DB.prepare("SELECT * FROM threads WHERE id = ?").bind(id).first();
  if (!thread) return json({ error: "Thread not found" }, 404);

  const { results: messages } = await env.DB.prepare(
    "SELECT * FROM messages WHERE thread_id = ? ORDER BY received_at ASC"
  ).bind(id).all();

  // Attach attachments to each message.
  for (const msg of messages as Record<string, unknown>[]) {
    const { results: atts } = await env.DB.prepare(
      "SELECT * FROM attachments WHERE message_id = ?"
    ).bind(msg.id).all();
    msg.attachments = atts;
    parseMessageArrays(msg);
  }

  (thread as Record<string, unknown>).messages = messages;
  return json(thread);
}

async function upsertThread(env: Env, body: ThreadBody): Promise<Response> {
  const now = new Date().toISOString();
  await env.DB.prepare(`
    INSERT INTO threads (id, subject, identity_id, last_message_at, message_count, is_read, is_starred, is_archived, is_trashed, snippet, participant_names, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id) DO UPDATE SET
      last_message_at = excluded.last_message_at,
      message_count = excluded.message_count,
      is_read = excluded.is_read,
      is_starred = excluded.is_starred,
      is_archived = excluded.is_archived,
      is_trashed = excluded.is_trashed,
      snippet = excluded.snippet,
      participant_names = excluded.participant_names,
      updated_at = excluded.updated_at
  `).bind(
    body.id, body.subject, body.identity_id, body.last_message_at,
    body.message_count ?? 1, body.is_read ? 1 : 0, body.is_starred ? 1 : 0,
    body.is_archived ? 1 : 0, body.is_trashed ? 1 : 0, body.snippet ?? "",
    body.participant_names ?? "", body.created_at ?? now, now
  ).run();
  return json({ ok: true });
}

// ── Messages ──────────────────────────────────────────────────────────────────

async function saveMessage(env: Env, body: MessageBody): Promise<Response> {
  const now = new Date().toISOString();
  await env.DB.prepare(`
    INSERT OR IGNORE INTO messages
      (id, thread_id, message_id, in_reply_to, "references", from_address, from_name,
       to_addresses, cc_addresses, bcc_addresses, reply_to, subject, body_text, body_html,
       snippet, original_to, direction, imap_uid, resend_id, is_read, is_draft,
       has_attachments, received_at, created_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `).bind(
    body.id, body.thread_id, body.message_id, body.in_reply_to ?? "",
    (body.references ?? []).join(" "),
    body.from_address, body.from_name ?? "",
    JSON.stringify(body.to_addresses ?? []),
    JSON.stringify(body.cc_addresses ?? []),
    JSON.stringify(body.bcc_addresses ?? []),
    body.reply_to ?? "", body.subject,
    body.body_text ?? "", body.body_html ?? "", body.snippet ?? "",
    body.original_to ?? "", body.direction ?? "inbound",
    body.imap_uid ?? null, body.resend_id ?? null,
    body.is_read ? 1 : 0, body.is_draft ? 1 : 0,
    body.has_attachments ? 1 : 0,
    body.received_at ?? now, now
  ).run();
  return json({ ok: true });
}

// ── Drafts ────────────────────────────────────────────────────────────────────

async function listDrafts(env: Env): Promise<Response> {
  const { results } = await env.DB.prepare(
    "SELECT * FROM drafts ORDER BY updated_at DESC"
  ).all();
  for (const d of results as Record<string, unknown>[]) parseMessageArrays(d);
  return json({ drafts: results });
}

async function saveDraft(env: Env, body: DraftBody): Promise<Response> {
  const now = new Date().toISOString();
  const id = body.id ?? crypto.randomUUID();
  await env.DB.prepare(`
    INSERT INTO drafts (id, thread_id, identity_id, to_addresses, cc_addresses, bcc_addresses,
      subject, body_text, body_html, in_reply_to, "references", is_reply, created_at, updated_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    ON CONFLICT(id) DO UPDATE SET
      to_addresses=excluded.to_addresses, subject=excluded.subject,
      body_text=excluded.body_text, body_html=excluded.body_html,
      updated_at=excluded.updated_at
  `).bind(
    id, body.thread_id ?? null, body.identity_id,
    JSON.stringify(body.to_addresses ?? []),
    JSON.stringify(body.cc_addresses ?? []),
    JSON.stringify(body.bcc_addresses ?? []),
    body.subject ?? "", body.body_text ?? "", body.body_html ?? "",
    body.in_reply_to ?? "", (body.references ?? []).join(" "),
    body.is_reply ? 1 : 0,
    body.created_at ?? now, now
  ).run();
  return json({ id });
}

async function deleteDraft(env: Env, id: string): Promise<Response> {
  await env.DB.prepare("DELETE FROM drafts WHERE id = ?").bind(id).run();
  return json({ ok: true });
}

// ── Sync ──────────────────────────────────────────────────────────────────────

async function syncPull(env: Env, body: SyncPullBody): Promise<Response> {
  const { client_id, d1_cursor } = body;
  const since = d1_cursor ?? "1970-01-01T00:00:00Z";

  const [{ results: threads }, { results: messages }, { results: drafts }, cursor] =
    await Promise.all([
      env.DB.prepare("SELECT * FROM threads WHERE updated_at > ? LIMIT 500").bind(since).all(),
      env.DB.prepare("SELECT * FROM messages WHERE created_at > ? LIMIT 500").bind(since).all(),
      env.DB.prepare("SELECT * FROM drafts WHERE updated_at > ? LIMIT 100").bind(since).all(),
      env.DB.prepare("SELECT imap_uid FROM sync_cursors WHERE client_id = ?").bind(client_id).first<{ imap_uid: number }>(),
    ]);

  for (const m of messages as Record<string, unknown>[]) parseMessageArrays(m);
  for (const d of drafts as Record<string, unknown>[]) parseMessageArrays(d);

  const nextCursor = new Date().toISOString();
  return json({
    threads,
    messages,
    drafts,
    next_cursor: nextCursor,
    last_imap_uid: cursor?.imap_uid ?? 0,
  });
}

async function syncPush(env: Env, body: SyncPushBody): Promise<Response> {
  const { client_id, messages, threads, drafts, last_imap_uid } = body;
  const now = new Date().toISOString();
  const batch: D1PreparedStatement[] = [];

  // Upsert messages.
  for (const m of (messages ?? [])) {
    batch.push(env.DB.prepare(`
      INSERT OR IGNORE INTO messages (id, thread_id, message_id, in_reply_to, "references",
        from_address, from_name, to_addresses, cc_addresses, bcc_addresses, reply_to, subject,
        body_text, body_html, snippet, original_to, direction, imap_uid, resend_id,
        is_read, is_draft, has_attachments, received_at, created_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
    `).bind(
      m.id, m.thread_id, m.message_id, m.in_reply_to ?? "",
      (m.references ?? []).join(" "),
      m.from_address, m.from_name ?? "",
      JSON.stringify(m.to_addresses ?? []),
      JSON.stringify(m.cc_addresses ?? []),
      JSON.stringify(m.bcc_addresses ?? []),
      m.reply_to ?? "", m.subject,
      m.body_text ?? "", m.body_html ?? "", m.snippet ?? "",
      m.original_to ?? "", m.direction ?? "inbound",
      m.imap_uid ?? null, m.resend_id ?? null,
      m.is_read ? 1 : 0, 0, m.has_attachments ? 1 : 0,
      m.received_at ?? now, now
    ));
  }

  // Upsert threads.
  for (const t of (threads ?? [])) {
    batch.push(env.DB.prepare(`
      INSERT INTO threads (id, subject, identity_id, last_message_at, message_count,
        is_read, is_starred, is_archived, is_trashed, snippet, created_at, updated_at)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?)
      ON CONFLICT(id) DO UPDATE SET
        last_message_at=excluded.last_message_at, message_count=excluded.message_count,
        is_read=excluded.is_read, snippet=excluded.snippet, updated_at=excluded.updated_at
    `).bind(
      t.id, t.subject, t.identity_id, t.last_message_at,
      t.message_count ?? 1, t.is_read ? 1 : 0, t.is_starred ? 1 : 0,
      t.is_archived ? 1 : 0, t.is_trashed ? 1 : 0, t.snippet ?? "",
      t.created_at ?? now, now
    ));
  }

  // Update sync cursor.
  if (last_imap_uid && client_id) {
    batch.push(env.DB.prepare(`
      INSERT INTO sync_cursors (client_id, imap_uid, d1_cursor, updated_at)
      VALUES (?, ?, ?, ?)
      ON CONFLICT(client_id) DO UPDATE SET imap_uid=excluded.imap_uid, updated_at=excluded.updated_at
    `).bind(client_id, last_imap_uid, now, now));
  }

  if (batch.length > 0) {
    await env.DB.batch(batch);
  }

  return json({ ok: true });
}

// ── Helpers ───────────────────────────────────────────────────────────────────

const BOOL_KEYS = new Set([
  "is_active", "is_read", "is_starred", "is_archived", "is_trashed",
  "is_draft", "has_attachments", "is_inline", "is_reply"
]);

function parseMessageArrays(msg: Record<string, unknown>) {
  msg.to_addresses = JSON.parse((msg.to_addresses as string) ?? "[]");
  msg.cc_addresses = JSON.parse((msg.cc_addresses as string) ?? "[]");
  msg.bcc_addresses = JSON.parse((msg.bcc_addresses as string) ?? "[]");
  msg.references = ((msg.references as string) ?? "").split(" ").filter(Boolean);
}

function castBools(obj: any): any {
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i++) castBools(obj[i]);
  } else if (obj !== null && typeof obj === "object") {
    for (const key of Object.keys(obj)) {
      if (BOOL_KEYS.has(key)) {
        obj[key] = !!obj[key];
      } else if (typeof obj[key] === "string" && obj[key].length === 19 && obj[key][10] === " ") {
        // SQLite datetime('now') produces "YYYY-MM-DD HH:MM:SS". Convert to ISO8601 for Go.
        obj[key] = obj[key].replace(" ", "T") + "Z";
      } else if (typeof obj[key] === "object") {
        castBools(obj[key]);
      }
    }
  }
  return obj;
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(castBools(data)), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}
