/**
 * Cloudflare Email Worker — Metadata Injector
 *
 * This worker sits between Cloudflare Email Routing and Gmail. It:
 * 1. Captures the envelope recipient (the @domain.tld address).
 * 2. Injects an X-Original-To header so the desktop client knows
 *    which virtual mailbox received the message.
 * 3. Writes a lightweight metadata record to D1 for early indexing
 *    (so the UI can show "new mail" before IMAP sync catches up).
 * 4. Forwards the enriched email to Gmail.
 *
 * Bindings required (wrangler.toml / secrets):
 *   - DB:             [[d1_databases]] binding
 *   - FORWARD_ADDRESS: wrangler secret put FORWARD_ADDRESS
 */

// ── Environment ───────────────────────────────────────────────────────────────
// DB is generated by `wrangler types` from wrangler.toml [[d1_databases]].
// FORWARD_ADDRESS is a secret — not in wrangler.toml, so we declare it here.
export interface Env {
  DB: D1Database;
  FORWARD_ADDRESS: string;
}

// ── Worker entry point ────────────────────────────────────────────────────────

export default {
  async email(
    message: ForwardableEmailMessage,
    env: Env,
    ctx: ExecutionContext
  ): Promise<void> {
    // ── 1. Capture envelope metadata ─────────────────────────────────────────
    const originalTo = message.to;     // e.g. "careers@yourdomain.com"
    const originalFrom = message.from; // sender's address
    const subject = message.headers.get("Subject") ?? "(no subject)";
    const messageId = message.headers.get("Message-ID") ?? "";
    const inReplyTo = message.headers.get("In-Reply-To") ?? "";
    const references = message.headers.get("References") ?? "";
    const receivedAt = new Date().toISOString();

    // ── 2. Write early-index record to D1 ────────────────────────────────────
    ctx.waitUntil(
      (async () => {
        try {
          await env.DB.prepare(`
            INSERT OR IGNORE INTO message_index
              (message_id, original_to, from_address, subject, in_reply_to, references, received_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
          `).bind(
            messageId,
            originalTo,
            originalFrom,
            subject,
            inReplyTo,
            references,
            receivedAt
          ).run();
        } catch (err) {
          console.error("D1 write failed:", err);
          // Non-fatal: mail delivery must not depend on D1 availability.
        }
      })()
    );

    // ── 3. Inject X-Original-To header and forward ────────────────────────────
    // Cloudflare only allows X-prefixed custom headers in message.forward().
    const customHeaders = new Headers();
    customHeaders.set("X-Original-To", originalTo);
    customHeaders.set("X-Mail-Worker", "mail-email-worker/1.0");

    try {
      await message.forward(env.FORWARD_ADDRESS, customHeaders);
    } catch (err) {
      console.error("Forward failed:", err);
      // Reject with a 550 so the sender gets a proper bounce.
      message.setReject(`Temporary delivery failure — please try again later.`);
    }
  },
} satisfies ExportedHandler<Env>;
